### ISSUE TITLE
`JAXOptMinimize.eval_and_update()` has no `forward_mode_differentiation` keyword argument

### ISSUE THREAD

**Issue by vandalt** [dfm/numpyro-ext#31]
Hi!

I got the error below when running the [Jaxoplanet transit fitting tutorial](https://jax.exoplanet.codes/en/latest/tutorials/transit/). I'm guessing this is due to an API change in how numpyro does optimization and SVI.

A simple fix that worked locally was to add that keyword argument in `JaxOptMinimize.eval_and_update()`, set it to false by default, and raise an error if it's set to `True` (so that an attempt to use it does not fail silently). I can submit a PR if this this is a good fix (I don't know if jaxopt supports forward differentiation like numpyro's solvers, in which case I guess it would be better to make it do that instead of raising an error).

Thanks!

<details>
<summary>Full error output</summary>

```python
TypeError                                 Traceback (most recent call last)
Cell In[7], line 22
      8     init_params = {
      9         "t0": T0,
     10         "logP": jnp.log(PERIOD),
   (...)
     15         "u": U,
     16     }
     17     run_optim = numpyro_ext.optim.optimize(
     18         model,
     19         init_strategy=numpyro.infer.init_to_value(values=init_params),
     20     )
---> 22 opt_params = run_optim(jax.random.PRNGKey(5), t, yerr, y=y)

File ~/repos/astro/exoplanet-dev/numpyro-ext/src/numpyro_ext/optim.py:86, in optimize.<locals>.run(rng_key, *args, **kwargs)
     84 state = svi.init(init_key, *args, **kwargs)
     85 for _ in range(num_steps):
---> 86     state, _ = svi.update(state, *args, **kwargs)
     87 info = getattr(state.optim_state[1], "state", None)
     88 params = svi.get_params(state)

File ~/repos/astro/exoplanet-dev/jaxoplanet/venv/lib/python3.11/site-packages/numpyro/infer/svi.py:285, in SVI.update(self, svi_state, forward_mode_differentiation, *args, **kwargs)
    273 rng_key, rng_key_step = random.split(svi_state.rng_key)
    274 loss_fn = _make_loss_fn(
    275     self.loss,
    276     rng_key_step,
   (...)
    283     mutable_state=svi_state.mutable_state,
    284 )
--> 285 (loss_val, mutable_state), optim_state = self.optim.eval_and_update(
    286     loss_fn, svi_state.optim_state, forward_mode_differentiation=forward_mode_differentiation
    287 )
    288 return SVIState(optim_state, mutable_state, rng_key), loss_val

TypeError: JAXOptMinimize.eval_and_update() got an unexpected keyword argument 'forward_mode_differentiation'
```

</details>

**Comment by dfm** [comment]
Thanks! Adding ref to related issue here: https://github.com/exoplanet-dev/jaxoplanet/issues/160

If you'd be up for opening a PR, that would be great! I think that it's possible that we could actually pass the `forward_mode_differentiation` argument where needed, rather than throwing an error, but I don't feel too strongly about that, and I rather get something working!

Furthermore, it looks like [jaxopt is being deprecated](https://github.com/google/jaxopt), so we shouldn't spend too much time thinking about this just now.
